import type { ProjectInput } from "../../lib/models/project";

export const legacyProjects: ProjectInput[] = [
  {
    slug: "qurvia-academy",
    title: "Qurvia Academy",
    tagline: "Online Islamic Quran Teaching Academy",
    description: "A modern online platform connecting students worldwide with qualified Quran teachers for live, interactive lessons.",
    longDescription: "Qurvia Academy is a comprehensive online Islamic Quran teaching platform designed to connect students worldwide with qualified Quran teachers. The platform supports live video sessions, progress tracking, structured curriculum management, and flexible scheduling to accommodate students across different time zones.",
    image: "/images/projects/qurvia academy.PNG",
    category: "Education",
    tech: ["Next.js", "React", "Node.js", "MongoDB"],
    url: "https://www.qurviaacademy.com/",
    features: [
      "Live interactive Quran lessons via video",
      "Student progress tracking dashboard",
      "Teacher management & profile system",
      "Structured curriculum with lesson plans",
      "Flexible scheduling & booking system",
      "Multi-timezone support for global students",
    ],
    year: "2024",
    highlight: "Connecting students with qualified Quran teachers globally",
  },
  {
    slug: "techsparrow",
    title: "TechSparrow",
    tagline: "Buy & Sell Phones and Tablets",
    description: "A marketplace platform for buying and selling phones and tablets with a clean, user-friendly interface.",
    longDescription: "TechSparrow is a marketplace platform specifically designed for buying and selling pre-owned phones and tablets. The platform features product listings, condition grading, secure checkout, seller dashboards, and a streamlined user experience for both buyers and sellers.",
    image: "/images/projects/techsparrow.PNG",
    category: "E-commerce",
    tech: ["React", "Node.js", "MongoDB", "Express"],
    url: "https://techsparrow.vercel.app/",
    features: [
      "Product listing management system",
      "Device condition grading system",
      "Secure buyer & seller transactions",
      "Advanced search & filter functionality",
      "Seller dashboard with analytics",
      "Mobile-responsive design",
    ],
    year: "2024",
  },
  {
    slug: "delbari",
    title: "Delbari Matrimonial",
    tagline: "Full-Stack Matrimonial Platform for Australia",
    description: "A comprehensive matrimonial and wedding platform for the Australian Muslim community with dynamic matchmaking and a vendor directory.",
    longDescription: "Delbari is a full-stack matrimonial platform built with Next.js and MongoDB, targeting the Australian Muslim community. It features a sophisticated matchmaking engine with advanced filters, tiered membership plans, a wedding vendor directory (venues, photographers, caterers, and more), real-life stories, and a blog section — all under one roof.",
    image: "/images/projects/delbari.PNG",
    category: "Matrimonial",
    tech: ["Next.js", "MongoDB", "Node.js", "TypeScript"],
    url: "https://delbari.com.au/",
    features: [
      "Dynamic profile matching with advanced filters (profession, sect, values)",
      "4-tier membership plans — Basic (Free), Standard ($49), Premium ($99), Elite ($199)",
      "Private photo settings with blur/hide until accepted",
      "Wedding vendor directory (venues, photographers, caterers, clothing)",
      "Blog with real-life stories & marriage tips",
      "Verified badge & featured profile placement",
      "Priority inbox and personalized match suggestions (Elite)",
      "Admin dashboard for member management",
    ],
    year: "2024",
    highlight: "Matrimonial + full wedding preparation directory under one roof",
  },
  {
    slug: "moda-fashion-hub",
    title: "Moda Fashion Hub",
    tagline: "Full-Stack Blog & Content Platform",
    description: "A full-stack blog application with role-based access for admins, publishers, and users — each with their own dedicated dashboard.",
    longDescription: "Moda Fashion Hub is a full-stack blog platform built with Next.js and MongoDB. The application features a robust role-based permission system with separate dashboards for administrators, publishers, and regular users. Publishers manage their own content pipeline while admins oversee moderation, analytics, and platform settings.",
    image: "/images/projects/modafashionhub.PNG",
    category: "Blog",
    tech: ["Next.js", "MongoDB", "Node.js", "TypeScript"],
    url: "https://modafashionhub.com/",
    features: [
      "Multi-role system: Admin, Publisher, and User",
      "Publisher-specific content creation dashboard",
      "Admin content moderation and management panel",
      "Rich text blog editor with media uploads",
      "Category & tag management system",
      "SEO-optimized article pages",
    ],
    year: "2024",
  },
  {
    slug: "myidoc-usa",
    title: "MyIDoc USA",
    tagline: "Telehealth Clinic Platform",
    description: "A highly ranked US telehealth clinic platform connecting patients with medical experts from the comfort of home.",
    longDescription: "MyIDoc USA is a full-stack telehealth platform built with Next.js and MongoDB. The application enables patients to connect with licensed medical professionals via video consultations, manage appointments, access prescriptions, and maintain their medical history — all from the comfort of home. Designed for the US healthcare market with HIPAA considerations.",
    image: "/images/projects/MyIdocUSA.JPG",
    category: "Healthcare",
    tech: ["Next.js", "MongoDB", "Node.js", "TypeScript"],
    features: [
      "Online video doctor consultations",
      "Appointment scheduling & management",
      "Patient medical history records",
      "Digital prescription management",
      "Telemedicine video integration",
      "Insurance & billing support",
      "Highly ranked US telehealth provider",
    ],
    year: "2023",
    highlight: "Highly Ranked Telehealth Clinic in USA",
  },
  {
    slug: "victory-villas",
    title: "Victory Villas",
    tagline: "Responsive Real Estate Website",
    description: "A fully responsive real estate website with dynamic blog and contact form with Gmail integration, built with React.js and Contentful.",
    longDescription: "Victory Villas is a modern real estate website developed with React.js and Contentful CMS. Features include a fully responsive design that looks great on all devices, a dynamic blog section powered by Contentful, and a functional contact form that sends submissions directly to Gmail. Delivers a seamless experience for every user.",
    image: "/images/projects/VictoryVillas.JPG",
    detailImages: ["/images/projects/VictoryVillas1.png", "/images/projects/VictoryVillas2.png"],
    category: "Real Estate",
    tech: ["React.js", "Contentful CMS", "Node.js"],
    features: [
      "Fully responsive design (mobile-first)",
      "Dynamic blog powered by Contentful CMS",
      "Contact form with direct Gmail integration",
      "Property listings showcase",
      "SEO-optimized pages for all devices",
      "Smooth, seamless user experience across devices",
    ],
    year: "2023",
  },
  {
    slug: "maidaan",
    title: "Maidaan Marketing",
    tagline: "Luxury Real Estate Platform",
    description: "A dynamic real estate platform with blog, career listings, and contact forms built with Next.js and Contentful for luxury property investors.",
    longDescription: "Maidaan is a real estate platform powered by Next.js and Contentful, targeting luxury property investors. The platform features dynamic blogs, career listings, and contact forms with an intuitive interface. Customers and investors can explore Property Ka Maidaan, learn about services, and stay up-to-date with the latest property news.",
    image: "/images/projects/Maidaan.JPG",
    category: "Real Estate",
    tech: ["Next.js", "Contentful CMS", "TypeScript"],
    features: [
      "Dynamic blog with Contentful CMS integration",
      "Career listings management system",
      "Contact & inquiry forms",
      "Luxury property showcase pages",
      "Responsive design across all devices",
      "SEO-optimized content & pages",
    ],
    year: "2023",
  },
  {
    slug: "vcc-website",
    title: "Virtual Card Selling (VCC)",
    tagline: "Full-Featured Virtual Card E-commerce Platform",
    description: "A secure VCC e-commerce website with authentication, admin activation, cart & checkout — built with React, Firebase, and Node.js.",
    longDescription: "A full-featured Virtual Card Selling (VCC) website built with React, Firebase, and Node.js. The platform features secure authentication, an admin-verified activation process with a $50 fee, complete e-commerce functionality (add to cart, checkout, instant VCC access), and a fully responsive design. Delivered with 100% client satisfaction.",
    image: "/images/projects/RussianShop.JPG",
    category: "E-commerce",
    tech: ["React.js", "Firebase", "Node.js"],
    features: [
      "Secure authentication & user login system",
      "Admin activation key verification with $50 fee",
      "Add to cart & full checkout flow",
      "Instant VCC access after purchase",
      "Fully responsive across all devices",
      "100% client satisfaction achieved",
    ],
    year: "2023",
    highlight: "100% client satisfaction with seamless user flow",
  },
  {
    slug: "ent-rhinoplasty-hub",
    title: "ENT & Rhinoplasty Hub",
    tagline: "Medical Practice Website",
    description: "Expert ENT and advanced rhinoplasty procedure website built with Next.js and Contentful CMS.",
    longDescription: "ENT & Rhinoplasty Hub is a professional medical practice website built with Next.js and Contentful. The site showcases expert ENT disease care and advanced rhinoplasty procedures, with detailed service pages, patient information sections, and an appointment booking interface. Designed with a medical-grade, professional aesthetic.",
    image: "/images/projects/entrhinoplasty.JPG",
    category: "Healthcare",
    tech: ["Next.js", "Contentful CMS", "TypeScrit"],
    url: "https://ent-rhino-git-main-abdlremans-projects.vercel.app/",
    features: [
      "Service showcasing for ENT & rhinoplasty",
      "Detailed patient information pages",
      "Appointment booking interface",
      "Contentful-powered content management",
      "Professional, medical-grade design",
      "Responsive across all devices",
    ],
    year: "2023",
  },
  {
    slug: "alharam-store",
    title: "Alharam Store",
    tagline: "E-commerce Platform",
    description: "A full-featured e-commerce store built with React.js and Contentful CMS for a seamless shopping experience.",
    longDescription: "Alharam Store is a comprehensive e-commerce platform built with React.js and Contentful CMS. The platform delivers a smooth shopping experience with rich product catalogs, category filters, shopping cart, and checkout functionality — all managed through Contentful's flexible CMS.",
    image: "/images/projects/alharam.PNG",
    category: "E-commerce",
    tech: ["React.js", "Contentful CMS"],
    url: "https://www.alharam.store/",
    features: [
      "Full product catalog with category management",
      "Shopping cart & seamless checkout",
      "Contentful-powered product management",
      "Responsive design for all devices",
      "Search & filter functionality",
    ],
    year: "2023",
  },
  {
    slug: "ifi-lifestyle",
    title: "IFI Lifestyle",
    tagline: "Fashion E-commerce Store",
    description: "A fashion e-commerce store built with React.js and Contentful with a modern, lifestyle-focused design.",
    longDescription: "IFI Lifestyle is a fashion e-commerce platform built with React.js and Contentful CMS. The store focuses on lifestyle-oriented fashion products with a modern, clean design, smooth browsing experience, and a seamless checkout flow — all content managed through Contentful.",
    image: "/images/projects/ifilifestyle.PNG",
    category: "E-commerce",
    tech: ["React.js", "Contentful CMS"],
    url: "https://www.ifilifestyle.com/",
    features: [
      "Fashion product catalog with rich imagery",
      "Category & filter navigation",
      "Contentful CMS product management",
      "Modern lifestyle-focused design",
      "Fully responsive across all devices",
    ],
    year: "2023",
  },
  {
    slug: "mcklunky",
    title: "MCKlunky",
    tagline: "UK-Based E-commerce Store",
    description: "A UK-based e-commerce store built with WordPress and WooCommerce, featuring a robust product catalog and smooth shopping experience.",
    longDescription: "MCKlunky is a UK-based e-commerce store built with WordPress and WooCommerce. The platform offers a comprehensive product catalog, secure payment processing, and a clean user interface tailored specifically for the UK market. Fully managed through WordPress for easy content updates.",
    image: "/images/projects/mcklunky.png",
    detailImages: ["/images/projects/mcklunky detail.png"],
    category: "E-commerce",
    tech: ["WordPress", "WooCommerce", "PHP"],
    url: "https://mcklunky.co.uk/",
    features: [
      "Full WooCommerce e-commerce functionality",
      "UK market-focused design & experience",
      "Comprehensive product catalog management",
      "Secure payment gateway integration",
      "Responsive mobile-first design",
    ],
    year: "2023",
  },
  {
    slug: "netmcn",
    title: "NetMCN",
    tagline: "YouTube-Related Services Website",
    description: "A professional service website for YouTube content creators and MCN (Multi-Channel Network) related services.",
    longDescription: "NetMCN is a professional services website designed for YouTube content creators and MCN (Multi-Channel Network) related services. The platform showcases the full range of YouTube-related service offerings, package pricing, and provides an inquiry interface for content creators looking to scale their channels.",
    image: "/images/projects/netmcn.png",
    detailImages: ["/images/projects/netmcndetail.png"],
    category: "SM Services",
    tech: ["React.js", "Next.js"],
    features: [
      "YouTube creator service showcasing",
      "MCN network information & offerings",
      "Pricing & package display",
      "Contact & inquiry system",
      "Creator-focused, engaging design",
    ],
    year: "2023",
  },
  {
    slug: "my-ecommerce-project",
    title: "E-Commerce Platform",
    tagline: "Full-Featured E-commerce with Reviews & Email Confirmation",
    description: "A complete e-commerce system with cart, order confirmation emails, customer reviews, and category filters — built with React.js and Firebase.",
    longDescription: "A full-featured e-commerce platform built with React.js and Firebase. The system includes a complete shopping cart with seamless checkout, instant order confirmation emails, a customer review and ratings system, category-based product filtering, and a fully responsive design for seamless mobile and desktop shopping.",
    image: "/images/projects/EcommerceWeb.JPG",
    category: "E-commerce",
    tech: ["React.js", "Firebase", "Node.js"],
    features: [
      "Shopping cart with seamless checkout flow",
      "Instant order confirmation emails",
      "Customer reviews & star ratings",
      "Category-based product filters",
      "Fully responsive design (mobile & desktop)",
    ],
    year: "2022",
  },
];
